---
name: Update Github Pages

'on':
  push:
    branches:
      - main

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    permissions:
      # This makes sure that this action has permissions to push to
      # the gh-pages branch.
      contents: "write"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: |
          nix build .#builder && ./result

      - run: |
          mkdir -p out/ && mv headshot.jpg out/ && mv resume.html out/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
