---
name: Update Github Pages

'on':
  push:
    branches:
      - main

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: |
          nix build .# && ./result

      - run: |
          mkdir -p out/ && mv headshot.jpg out/ && mv resume.html out/index.html

      #
      # For this to work on new repositories you'd seem to have to go
      # to the "repository settings" -> "Actions" -> "General" ->
      # "Workflow permissions" and select "Read and write permissions"
      #
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
